theme: jekyll-theme-minimal
title: Kuldars Homepage
description: idk i am doing sth,
 I am too lazy to write an essay about what I dont know, like why I am studying in this school.
 Besides just wanting to learn programming and not knowing anything about it.